

name: Docker HUB config
run-name: Workflow Docker HUB config
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.ACR_REGISTRY_NAME}}
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}              
      - name: Build and push
        run: |
          docker build . -t ${{secrets.ACR_REGISTRY_NAME}}/prueba-gh:${{ github.sha }}
          docker push ${{secrets.ACR_REGISTRY_NAME}}/prueba-gh:${{ github.sha }}
